{
    'name': "SCI Support Ticket",
    'version': "1.0.11",
    'author': "Sythil Tech, Adaptive City",
    'category': "Tools",
    'support': "steven@sythiltech.com.au",
    'summary': "A helpdesk / support ticket system for your website",
    'description': "A helpdesk / support ticket system for your website",
    'license':'LGPL-3',
    'data': [
        'data/ir.module.category.csv',
        'data/res.groups.xml',
        'views/website_support_ticket_templates.xml',
        'views/website_support_ticket_compose_views.xml',
        'views/website_support_ticket_close_views.xml',
        'views/website_support_ticket_views.xml',
        'views/website_support_ticket_tag_views.xml',
        'views/maintenance_request_views.xml',
        'views/menus.xml',
        'data/website.menu.csv',
        'security/ir.model.access.csv',
        'static/views/view.xml'
    ],
    'demo': [],
    'depends': ['mail', 'web', 'website', 'resource', 'base', 'vnitpro_maintenance'],
    'images':[
        'static/description/3.jpg',
        'static/description/1.jpg',
        'static/description/2.jpg',
        'static/description/4.jpg',
        'static/description/5.jpg',
        'static/description/6.jpg',
    ],
    'installable': True,
}